image: gitpod/workspace-mongodb
ports:
  - port: 5000
  - port: 27017
tasks:
  - command: mongod
  - command: pip3 install -r requirements.txt && python3 data_acquire.py && python3 app.py
vscode:
  extensions:
    - ms-python.python@2019.9.34911:NHtRMp5fFB2KUUw72DlGug==